/**
 * What a saved node graph is, on the wire and in the `graphs.definition` blob.
 *
 * One definition, read by three things that must not drift: the editor that draws it, the daemon
 * that runs it, and the validator below that both of them call. That is the same argument
 * `NodeDefinition` makes in `@vrcz/plugin-api` — see PLAN.md §Node type registration — one level up.
 *
 * ## What is checked here, and what is not
 *
 * {@link validateGraphDocument} answers everything that can be decided from the document alone:
 * shape, duplicate ids, edges pointing at nodes that are not there, ports wired to themselves,
 * cycles, and the ceilings. It deliberately does **not** check port *types* or whether a node type
 * exists — both need the node registry, which lives in the daemon and is populated by running
 * plugins. That check is `checkEdge`, and it runs on save in the daemon and live in the editor.
 *
 * Both halves run twice on purpose, in the editor and again in the daemon, because the frontend is a
 * client and clients lie.
 *
 * ## Why this lives in `@vrcz/shared` rather than `@vrcz/plugin-api`
 *
 * A graph is not part of the plugin API: plugins contribute node *types*, they do not author or read
 * graphs (decision 206 keeps graphs first-party and session-token only). And the dependency runs one
 * way — `@vrcz/plugin-api` imports this package, so this package cannot import it back. The one cost
 * of that is {@link GraphNodeConfig}, which has to mirror `NodeConfigValues` structurally; the
 * daemon asserts the two agree at compile time, since it is the one place that imports both.
 */

/**
 * A node instance's configured values, keyed by field id.
 *
 * The wire mirror of `NodeConfigValues` from `@vrcz/plugin-api/nodes`, which cannot be imported here
 * without a cycle. `daemon/src/graphs/types.ts` holds an assignability check in both directions, so
 * a change to either one is a compile error rather than a shape that quietly disagrees.
 */
export type GraphNodeConfig = Readonly<Record<string, string | number | boolean>>;

/** Canvas coordinates. Editor-only: the runtime never reads these. */
export interface GraphNodePosition {
  readonly x: number;
  readonly y: number;
}

export interface GraphNode {
  /** Unique within the graph. Generated by the editor; an edge references this, never the type. */
  readonly id: string;
  /** The qualified node type: `<pluginId>/<nodeId>`, or the reserved namespace for a built-in. */
  readonly type: string;
  readonly position: GraphNodePosition;
  readonly config: GraphNodeConfig;
  /**
   * The `nodeDefinitionHash` of the definition this node was configured against.
   *
   * This is what makes an incompatible plugin update visible instead of silent. On load the daemon
   * compares it against the definition the plugin registers now; a mismatch **blocks the graph**
   * until the user migrates it in the editor, rather than rewiring a graph they already armed.
   * Absent for a node saved before its type was ever registered, which is not an error — a graph
   * referencing a stopped plugin is a normal state.
   */
  readonly defHash?: string;
  /**
   * Stop the run here, before this node executes, and wait for a person.
   *
   * Part of the document rather than a scribble the editor keeps to itself, for the same reason a
   * node's position is: it is something the author placed. A breakpoint that evaporated when the
   * tab closed would be useless for the case it exists for, which is a graph that misbehaves half
   * an hour later on a fire nobody was sitting there watching.
   *
   * **Honoured only while the graph is in debug mode.** A breakpoint forgotten in a saved graph
   * must not be able to park a run forever on a machine nobody is looking at, and tying it to the
   * switch the author flips when they sit down to debug is the smallest rule that guarantees it.
   */
  readonly breakpoint?: boolean;
}

/** One end of an edge: a node instance and one of its ports. */
export interface GraphEdgeEnd {
  readonly node: string;
  readonly port: string;
}

export interface GraphEdge {
  readonly id: string;
  readonly from: GraphEdgeEnd;
  readonly to: GraphEdgeEnd;
}

/** The whole document. Everything the editor saves and the runtime walks. */
export interface GraphDocument {
  readonly nodes: readonly GraphNode[];
  readonly edges: readonly GraphEdge[];
}

/**
 * What happens when a trigger fires while a run of the same graph is still in flight.
 *
 * The author's choice rather than one imposed default, because neither is right for everyone:
 * instance joins arrive in bursts, so serialising by fiat makes a graph lag the event stream, and
 * dropping by fiat loses events. Whatever the mode, a fire that is not honoured is **recorded** as
 * `graph.run.dropped` — an automation that silently skips is indistinguishable from a broken one.
 */
export const GRAPH_CONCURRENCY_MODES = ["parallel", "queue", "drop"] as const;

export type GraphConcurrency = (typeof GRAPH_CONCURRENCY_MODES)[number];

export function isGraphConcurrency(value: unknown): value is GraphConcurrency {
  return (
    typeof value === "string" && (GRAPH_CONCURRENCY_MODES as readonly string[]).includes(value)
  );
}

/**
 * The states a run can be in while it still exists.
 *
 * There is no `finished` or `failed`: a run that ended is deleted from `graph_runs` and its record
 * is an `events` row with a `graph.*` kind. See `012_graphs.sql`.
 */
export const GRAPH_RUN_STATUSES = ["queued", "running", "waiting"] as const;

export type GraphRunStatus = (typeof GRAPH_RUN_STATUSES)[number];

/** Ceilings on the document itself. The runtime's own ceilings are separate; see PLAN.md §Phase 4. */
export const MAX_GRAPH_NODES = 256;
export const MAX_GRAPH_EDGES = 512;
export const MAX_GRAPH_NAME = 120;
export const MAX_GRAPH_DESCRIPTION = 2000;

/** One graph as the control API reports it, without its document. */
export interface GraphSummary {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  /** The user wants this graph to run. Its triggers are armed. */
  readonly enabled: boolean;
  /** Dry-run has been lifted, so outbound actions really happen. Never implied by `enabled`. */
  readonly armed: boolean;
  /**
   * The author is debugging this graph.
   *
   * A third switch rather than a client-side preference, and it buys three things that only the
   * daemon can give: every run records a {@link GraphTrace}, a failure that `on error` swallowed is
   * said out loud instead of vanishing into a wire, and `breakpoint` nodes actually park the run.
   *
   * Per graph, because that is the unit somebody debugs. A daemon-wide switch would mean the one
   * graph you are looking at costs the same as the eleven you are not, and the traces are the
   * expensive half: they hold what every node produced, which is the whole point of them.
   */
  readonly debug: boolean;
  readonly concurrency: GraphConcurrency;
  /** The default acting account. Null once the account it named is removed. */
  readonly accountId: string | null;
  /** Why the daemon switched this graph off, when it was the daemon that did it. */
  readonly disabledReason: string | null;
  readonly nodeCount: number;
  /**
   * The type ids of this graph's triggers, in document order.
   *
   * Free here — the daemon already parses the document to count the nodes — and it is what lets the
   * list say *what a graph watches for* rather than only how big it is. Type ids rather than titles,
   * because a title belongs to whoever registered the node and the client has that catalogue
   * already; sending a resolved title would freeze it at the moment the row was read.
   */
  readonly triggerTypes: readonly string[];
  /** When a run of this graph last started, or null if one never has. */
  readonly lastRunAt: number | null;
  readonly createdAt: number;
  readonly updatedAt: number;
}

export interface Graph extends GraphSummary {
  readonly definition: GraphDocument;
  /**
   * Node ids whose type has changed since the graph was saved.
   *
   * Computed by comparing each node's stored `defHash` against the definition registered right now.
   * A node whose type is not registered at all is **not** here: that is "the plugin is stopped",
   * which is a different sentence and a different fix. Empty for a graph that has never been saved
   * against a registered type, since there is nothing to compare.
   */
  readonly staleNodes: readonly string[];
}

/**
 * A graph as it leaves this machine, and arrives on another.
 *
 * **Secrets cannot be in here, and that is a property rather than a filter.** A secret never enters
 * the document in the first place (decision 213) — it lives in the credential store keyed by graph,
 * node and field — so an export carries no token even if nobody remembers to strip one.
 *
 * `nodeTypes` records what the graph was built against. On import it is what lets the daemon say
 * "this needs a plugin you do not have" instead of creating a graph that silently does nothing.
 */
export interface GraphExport {
  /** Bumped only if the shape changes in a way an older build cannot read. */
  readonly version: 1;
  readonly exportedAt: number;
  readonly name: string;
  readonly description: string;
  readonly concurrency: GraphConcurrency;
  readonly definition: GraphDocument;
  readonly nodeTypes: readonly { readonly qualifiedId: string; readonly defHash?: string }[];
}

/** What an import produced, and what it could not. */
export interface GraphImportResult {
  readonly graph: Graph;
  /** Node types this machine does not have. The graph is created anyway, disabled. */
  readonly missing: readonly string[];
  /** Node types present but changed since the export. */
  readonly changed: readonly string[];
}

/** One of the graphs vrc.zip ships, so the first canvas is an edit rather than a blank page. */
export interface GraphTemplate {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly definition: GraphDocument;
}

/** A run that has not finished. Live state, straight off `graph_runs`. */
export interface GraphRunSummary {
  readonly id: string;
  readonly graphId: string;
  readonly triggerNode: string;
  readonly status: GraphRunStatus;
  /**
   * Captured when the run started, not read from the graph when an action executes: arming a graph
   * must not turn an in-flight rehearsal into the real thing.
   */
  readonly dryRun: boolean;
  readonly waitNode: string | null;
  readonly resumeAt: number | null;
  readonly startedAt: number;
  readonly updatedAt: number;
  /**
   * The last node this run executed, so the editor can show where it is. Null before the first one.
   *
   * The *last executed* rather than the *currently executing*, and the difference is one node: the
   * row is rewritten at each node boundary, so a node that is mid-await is not in here yet. Naming
   * it "current" would promise a precision the persistence model does not have.
   */
  readonly currentNode: string | null;
  /** Where each loop currently is. Empty unless a `For each` is iterating right now. */
  readonly loops: readonly { readonly nodeId: string; readonly at: number; readonly of: number }[];
  /**
   * The node this run is parked **on** waiting for a person, rather than for a clock.
   *
   * A `Wait` and a breakpoint are the same row in `graph_runs` and are told apart by one thing: a
   * `Wait` always has a `resumeAt` and a breakpoint never does. So this is derived rather than
   * stored, which is what keeps the two from being able to disagree.
   */
  readonly pausedNode: string | null;
}

/**
 * What one node did, once.
 *
 * The values are here because they are the question. "Which node failed" is already answered by
 * `graph.run.failed` in the feed; what nobody could answer was *what was on the wire* — and on a
 * canvas of forty nodes that is the difference between reading a graph and guessing at it.
 *
 * Every value has been through {@link GRAPH_TRACE_VALUE_LIMIT}, so what arrives here is a summary
 * and says so. A trace is evidence for a person reading it, never something to replay a run from.
 */
export interface GraphTraceStep {
  readonly nodeId: string;
  /** `ok` ran, `error` threw, `skipped` was settled dead by an upstream port producing nothing. */
  readonly status: "ok" | "error" | "skipped";
  /** When it started, and how long it took. Unix ms, like every timestamp here. */
  readonly at: number;
  readonly ms: number;
  /** What it read, by input port. Absent for a skip and for a trigger, which reads nothing. */
  readonly inputs?: Readonly<Record<string, unknown>>;
  /** What it produced, by output port. A port missing from here is a dead wire downstream. */
  readonly outputs?: Readonly<Record<string, unknown>>;
  /** The failure. Present exactly when `status` is `error`. */
  readonly message?: string;
  /**
   * The author wired `on error` onward, so the run carried on.
   *
   * The single most useful bit in the whole trace: an unhandled failure ends the run and is loud,
   * and a handled one is a node that quietly did nothing while the graph reported success.
   */
  readonly handled?: boolean;
}

/**
 * One recorded run, kept only for a graph in debug mode.
 *
 * Not an `events` row, unlike every other piece of run history, and the reason is size: this holds
 * what flowed through every wire, which is exactly the sort of thing the feed must not fill up
 * with. It lives in its own table, bounded by count per graph rather than by age, and it is deleted
 * with the graph.
 */
export interface GraphTrace {
  readonly runId: string;
  readonly graphId: string;
  readonly triggerNode: string;
  readonly outcome: "finished" | "failed";
  readonly dryRun: boolean;
  /** The node the run died on, and its message. Both null when the run finished. */
  readonly failedNode: string | null;
  readonly message: string | null;
  /** In execution order. Truncated at {@link GRAPH_TRACE_STEP_LIMIT}, oldest kept. */
  readonly steps: readonly GraphTraceStep[];
  readonly startedAt: number;
  readonly finishedAt: number;
}

/**
 * How many runs of one graph are kept.
 *
 * Small on purpose. A trace answers "what did it just do", and the tenth-oldest run of a graph
 * firing every minute is not evidence anybody is going to read — it is disk.
 */
export const GRAPH_TRACE_LIMIT = 10;

/** Steps kept per trace. A `For each` over a thousand items is a run nobody reads step by step. */
export const GRAPH_TRACE_STEP_LIMIT = 300;

/** How much of one port value is kept, as JSON characters, before it is cut and marked. */
export const GRAPH_TRACE_VALUE_LIMIT = 512;

/**
 * What one node of a graph is remembering, so the editor can offer to forget it.
 *
 * The list exists so the button appears **only** where there is something to forget. The alternative
 * was a flag on `NodeDefinition` saying "this node remembers", which every definition would have to
 * set honestly and which would change the hash of the two that already exist — marking every saved
 * graph using them stale to add a button. Asking what is actually stored costs one grouped query and
 * cannot be wrong.
 */
export interface GraphMemoryEntry {
  readonly nodeId: string;
  /** How many keys. A per-person cooldown has one per person. */
  readonly entries: number;
  readonly updatedAt: number;
}

/**
 * One named store: data a graph put somewhere other graphs can read.
 *
 * Not scoped to a graph, and deliberately so — deleting a graph leaves its stores alone, because
 * the graph beside it may be reading them. See `014_graph_stores.sql`.
 */
export interface GraphStoreSummary {
  readonly name: string;
  readonly description: string;
  readonly entries: number;
  readonly createdAt: number;
  readonly updatedAt: number;
}

/**
 * One entry in a store, as the Stores panel shows it.
 *
 * `collection` is the raw column — `''`, `map:x`, `set:x`, `list` — and `kind`/`name` are it split
 * into what a person reads. Both, because the panel shows the friendly halves and a delete has to
 * name the exact row.
 */
export interface GraphStoreEntry {
  readonly collection: string;
  readonly kind: "value" | "map" | "set" | "list";
  /** The collection's name. Empty for a plain value, whose name is its key. */
  readonly name: string;
  readonly key: string;
  /** Already decoded. The column is JSON text; nothing downstream should parse it twice. */
  readonly value: unknown;
  readonly updatedAt: number;
}

/** Creating a graph. The two switches are absent on purpose: a new graph is off and unarmed. */
export interface GraphCreate {
  readonly name: string;
  readonly description?: string;
  readonly concurrency?: GraphConcurrency;
  readonly accountId?: string | null;
  readonly definition?: GraphDocument;
}

/** Saving a graph. Also switch-free — enabling and arming are their own routes and own gestures. */
export interface GraphUpdate {
  readonly name?: string;
  readonly description?: string;
  readonly concurrency?: GraphConcurrency;
  readonly accountId?: string | null;
  readonly definition?: GraphDocument;
}

/**
 * One node type as the palette sees it.
 *
 * `definition` is deliberately untyped here: `NodeDefinition` lives in `@vrcz/plugin-api`, which
 * imports this package, so naming it would be a cycle. Every consumer that needs the shape already
 * depends on that package and casts once — the daemon when it registers, the editor when it draws.
 *
 * `owner` is `vrcz` for a built-in and a plugin id otherwise; `available` says whether the type is
 * registered *right now*. A graph referencing an unavailable type is paused rather than broken, and
 * the palette greys it rather than hiding it — a node that vanished would hide the one fact that
 * explains why a graph stopped.
 */
export interface NodeTypeSummary {
  readonly qualifiedId: string;
  readonly owner: string;
  readonly available: boolean;
  readonly definition: unknown;
}

/* -------------------------------------------------------------------------------------------- */
/* Validation                                                                                     */
/* -------------------------------------------------------------------------------------------- */

/**
 * A validation failure, carrying the path to the thing that is wrong.
 *
 * Same contract as `validateNodeDefinition` and `validateUINode` in `@vrcz/plugin-api`: a result
 * rather than a throw, and every message names a path, because the only person who can fix this is
 * the one looking at the canvas.
 */
export interface GraphIssue {
  readonly path: string;
  readonly message: string;
}

export interface GraphValidation {
  readonly ok: boolean;
  readonly issues: readonly GraphIssue[];
}

const OK: GraphValidation = { ok: true, issues: [] };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isConfigValue(value: unknown): value is string | number | boolean {
  return (
    typeof value === "string" ||
    typeof value === "boolean" ||
    (typeof value === "number" && Number.isFinite(value))
  );
}

/**
 * Checks everything decidable without the node registry, and returns every problem rather than the
 * first — a canvas that reports one broken edge per save is a canvas nobody finishes fixing.
 */
export function validateGraphDocument(value: unknown): GraphValidation {
  const issues: GraphIssue[] = [];
  if (!isRecord(value)) return { ok: false, issues: [{ path: "", message: "not an object" }] };

  const nodes = value.nodes;
  const edges = value.edges;
  if (!Array.isArray(nodes)) issues.push({ path: "nodes", message: "must be an array" });
  if (!Array.isArray(edges)) issues.push({ path: "edges", message: "must be an array" });
  if (issues.length > 0) return { ok: false, issues };

  const nodeList = nodes as unknown[];
  const edgeList = edges as unknown[];
  if (nodeList.length > MAX_GRAPH_NODES) {
    issues.push({ path: "nodes", message: `more than ${MAX_GRAPH_NODES} nodes` });
  }
  if (edgeList.length > MAX_GRAPH_EDGES) {
    issues.push({ path: "edges", message: `more than ${MAX_GRAPH_EDGES} edges` });
  }

  const ids = new Set<string>();
  nodeList.forEach((node, i) => {
    const path = `nodes[${i}]`;
    if (!isRecord(node)) {
      issues.push({ path, message: "not an object" });
      return;
    }
    const id = node.id;
    if (typeof id !== "string" || id === "") {
      issues.push({ path: `${path}.id`, message: "must be a non-empty string" });
    } else if (ids.has(id)) {
      issues.push({ path: `${path}.id`, message: `duplicate node id "${id}"` });
    } else {
      ids.add(id);
    }
    if (typeof node.type !== "string" || node.type === "") {
      issues.push({ path: `${path}.type`, message: "must be a non-empty node type id" });
    }
    const position = node.position;
    if (
      !isRecord(position) ||
      typeof position.x !== "number" ||
      typeof position.y !== "number" ||
      !Number.isFinite(position.x) ||
      !Number.isFinite(position.y)
    ) {
      issues.push({ path: `${path}.position`, message: "must be finite {x, y}" });
    }
    const config = node.config;
    if (!isRecord(config)) {
      issues.push({ path: `${path}.config`, message: "must be an object" });
    } else {
      for (const [key, entry] of Object.entries(config)) {
        if (!isConfigValue(entry)) {
          issues.push({
            path: `${path}.config.${key}`,
            message: "must be a string, a finite number, or a boolean",
          });
        }
      }
    }
    if (node.defHash !== undefined && typeof node.defHash !== "string") {
      issues.push({ path: `${path}.defHash`, message: "must be a string when present" });
    }
    if (node.breakpoint !== undefined && typeof node.breakpoint !== "boolean") {
      issues.push({ path: `${path}.breakpoint`, message: "must be a boolean when present" });
    }
  });

  const edgeIds = new Set<string>();
  const wiredInputs = new Set<string>();
  const adjacency = new Map<string, string[]>();
  edgeList.forEach((edge, i) => {
    const path = `edges[${i}]`;
    if (!isRecord(edge)) {
      issues.push({ path, message: "not an object" });
      return;
    }
    const id = edge.id;
    if (typeof id !== "string" || id === "") {
      issues.push({ path: `${path}.id`, message: "must be a non-empty string" });
    } else if (edgeIds.has(id)) {
      issues.push({ path: `${path}.id`, message: `duplicate edge id "${id}"` });
    } else {
      edgeIds.add(id);
    }

    const resolveEnd = (side: "from" | "to", end: unknown): GraphEdgeEnd | null => {
      if (!isRecord(end) || typeof end.node !== "string" || typeof end.port !== "string") {
        issues.push({ path: `${path}.${side}`, message: "must be {node, port}" });
        return null;
      }
      if (!ids.has(end.node)) {
        issues.push({ path: `${path}.${side}.node`, message: `no node "${end.node}"` });
        return null;
      }
      return { node: end.node, port: end.port };
    };

    // Both sides are resolved before the early return, so a broken edge reports both ends rather
    // than sending the user back for a second save to hear about the other one.
    const from = resolveEnd("from", edge.from);
    const to = resolveEnd("to", edge.to);
    if (from === null || to === null) return;
    if (from.node === to.node) {
      issues.push({ path, message: "a node cannot be wired to itself" });
      return;
    }
    // One edge per input port. Two producers for one input has no defined merge, and a graph that
    // picks whichever arrived last is a graph that behaves differently on a busy evening.
    const inputKey = `${to.node}.${to.port}`;
    if (wiredInputs.has(inputKey)) {
      issues.push({ path: `${path}.to`, message: `input "${inputKey}" already has an edge` });
    } else {
      wiredInputs.add(inputKey);
    }
    const out = adjacency.get(from.node);
    if (out === undefined) adjacency.set(from.node, [to.node]);
    else out.push(to.node);
  });

  const cycle = findCycle(ids, adjacency);
  if (cycle !== null) {
    issues.push({ path: "edges", message: `cycle: ${cycle.join(" -> ")}` });
  }

  return issues.length === 0 ? OK : { ok: false, issues };
}

/**
 * The first cycle reachable in the graph, as the path that closes it, or null.
 *
 * Iterative rather than recursive: the depth is bounded by {@link MAX_GRAPH_NODES}, but this runs on
 * a document that arrived over HTTP, and a validator that can blow the stack on hostile input is a
 * denial of service in the shape of a helper.
 */
function findCycle(
  ids: ReadonlySet<string>,
  adjacency: ReadonlyMap<string, string[]>,
): string[] | null {
  const WHITE = 0;
  const GREY = 1;
  const BLACK = 2;
  const colour = new Map<string, number>();
  for (const id of ids) colour.set(id, WHITE);

  for (const root of ids) {
    if (colour.get(root) !== WHITE) continue;
    // Each frame is a node plus how far through its successors we are.
    const stack: { node: string; next: number }[] = [{ node: root, next: 0 }];
    colour.set(root, GREY);
    while (stack.length > 0) {
      const frame = stack[stack.length - 1];
      if (frame === undefined) break;
      const successors = adjacency.get(frame.node) ?? [];
      if (frame.next >= successors.length) {
        colour.set(frame.node, BLACK);
        stack.pop();
        continue;
      }
      const next = successors[frame.next];
      frame.next += 1;
      if (next === undefined) continue;
      const state = colour.get(next);
      if (state === GREY) {
        const start = stack.findIndex((f) => f.node === next);
        const path = stack.slice(start === -1 ? 0 : start).map((f) => f.node);
        path.push(next);
        return path;
      }
      if (state === WHITE) {
        colour.set(next, GREY);
        stack.push({ node: next, next: 0 });
      }
    }
  }
  return null;
}

/** Every node with no incoming edge — the roots a run can start from. */
export function graphRoots(document: GraphDocument): string[] {
  const targets = new Set(document.edges.map((edge) => edge.to.node));
  return document.nodes.filter((node) => !targets.has(node.id)).map((node) => node.id);
}

/**
 * The nodes reachable from `start`, including it.
 *
 * A run walks only what its own trigger reaches, which is what lets one graph hold several trigger
 * roots without a fire running branches that have no inputs.
 */
export function reachableFrom(document: GraphDocument, start: string): Set<string> {
  const out = new Map<string, string[]>();
  for (const edge of document.edges) {
    const list = out.get(edge.from.node);
    if (list === undefined) out.set(edge.from.node, [edge.to.node]);
    else list.push(edge.to.node);
  }
  const seen = new Set<string>();
  const queue = [start];
  while (queue.length > 0) {
    const node = queue.pop();
    if (node === undefined || seen.has(node)) continue;
    seen.add(node);
    for (const next of out.get(node) ?? []) if (!seen.has(next)) queue.push(next);
  }
  return seen;
}

/**
 * The `foreach` output ports that lead **into** the body, and the ones that lead **past** it.
 *
 * Named here rather than in the daemon's intrinsics because the canvas has to draw the same
 * boundary the engine walks. Two copies of this split is two answers to "is this node in the loop",
 * and the one on screen would be the one nobody tested.
 */
export const FOREACH_BODY_PORTS: readonly string[] = ["item", "index"];
export const FOREACH_AFTER_PORTS: readonly string[] = ["done", "results"];

/**
 * Which nodes belong to each loop's body.
 *
 * The body is what `item` and `index` reach, minus what `done` and `results` reach. That
 * subtraction is what lets one node sit after the loop *and* read the body — it is excluded from
 * the body, runs once in the outer scope, and sees the last iteration. Anything else would need a
 * second kind of edge to say "this one is after the loop", which is a concept the canvas does not
 * have and would have to explain.
 *
 * `loopIds` rather than a type check, because the type id lives in the daemon's reserved namespace
 * and this module is a leaf that may not import it.
 */
export function foreachBodies(
  document: GraphDocument,
  loopIds: Iterable<string>,
): Map<string, Set<string>> {
  const bodies = new Map<string, Set<string>>();
  for (const id of loopIds) {
    const after = reachableFromPorts(document, id, FOREACH_AFTER_PORTS);
    const body = reachableFromPorts(document, id, FOREACH_BODY_PORTS);
    for (const node of after) body.delete(node);
    body.delete(id);
    bodies.set(id, body);
  }
  return bodies;
}

/** Everything downstream of one node's named output ports, excluding the node itself. */
function reachableFromPorts(
  document: GraphDocument,
  nodeId: string,
  ports: readonly string[],
): Set<string> {
  const out = new Set<string>();
  for (const edge of document.edges) {
    if (edge.from.node !== nodeId || !ports.includes(edge.from.port)) continue;
    for (const id of reachableFrom(document, edge.to.node)) out.add(id);
  }
  out.delete(nodeId);
  return out;
}

/**
 * The loop a node belongs to, when loops are nested.
 *
 * The innermost one, always — the same scoping every language gives a `break`, so a `Collect` drawn
 * inside two loops appends to the one it is drawn in. The rule is structural rather than a size
 * comparison: a candidate is innermost when no other candidate loop node sits inside its body.
 * Returns null for a node that is in no body at all.
 */
export function innermostLoop(
  bodies: ReadonlyMap<string, ReadonlySet<string>>,
  nodeId: string,
): string | null {
  const candidates = [...bodies.entries()].filter(([, body]) => body.has(nodeId)).map(([id]) => id);
  for (const id of candidates) {
    const body = bodies.get(id);
    if (body === undefined) continue;
    if (!candidates.some((other) => other !== id && body.has(other))) return id;
  }
  return candidates[0] ?? null;
}
