/**
 * `@vrcz/shared` — the single source of truth for anything the daemon, proxy, UI, and docs must
 * agree on: event types, the scope registry, and wire protocol types.
 *
 * Nothing here may import from `@vrcz/daemon`, `@vrcz/api`, or `@vrcz/ui`. This package is a leaf.
 */

export {
  DEFAULT_CONTROL_PORT,
  DEFAULT_FORWARD_PROXY_PORT,
  DEFAULT_HOSTNAME,
  DEFAULT_PROXY_PORT,
  DEFAULT_UI_PORT,
  EMBEDDED_UI_PREFIX,
  launchUrl,
  SESSION_COOKIE,
  TOKEN_HEADER,
  TOKEN_QUERY_PARAM,
} from "./config.ts";
export {
  type AccountEventKind,
  BUS_EVENT_KINDS,
  type BusEventKind,
  type ConsentEventKind,
  type ContentEventKind,
  ECONOMY_CHANGE_ASPECTS,
  type EconomyChangeAspect,
  type EconomyEventKind,
  EVENT_FAMILIES,
  type EventFamily,
  type EventKind,
  type FieldChange,
  type FriendEventKind,
  familyOf,
  type GamelogEventKind,
  type GroupEventKind,
  type InstanceEventKind,
  isBusEventKind,
  type KnownEventKind,
  type NotificationEventKind,
  type PipelineEventKind,
  PROFILE_CHANGE_ASPECTS,
  type ProfileChangeAspect,
  type SessionEventKind,
  type UserEventKind,
} from "./events.ts";
export { isJsonObject, type JsonObject, type JsonValue } from "./json.ts";
export {
  ALL_SCOPES,
  DEFAULT_SCOPES,
  expandSuperWildcard,
  expandWildcard,
  isDangerousScope,
  isScope,
  NATIVE_SCOPES,
  SCOPES,
  type Scope,
  type ScopeDefinition,
} from "./scopes.ts";
export { APP_NAME, APP_VERSION, PLUGIN_API_PROTOCOL_MAJOR } from "./version.ts";
export {
  AVATAR_ID_PATTERN,
  FILE_ID_PATTERN,
  fileIdFromImageUrl,
} from "./vrchat-files.ts";
export {
  type AccountConnection,
  type AccountRateCeiling,
  type AppAuditEntry,
  type AuditOutcome,
  type AvatarDetail,
  type AvatarFileResolution,
  type ControlAccount,
  type DaemonStatus,
  type EventKindCount,
  type EventQuery,
  type FeedEvent,
  type FriendPresence,
  type FriendStatus,
  type GameSession,
  type GroupGalleryImagePage,
  type GroupGalleryImageSummary,
  type GroupGallerySummary,
  type GroupInstanceList,
  type GroupInstanceSummary,
  type GroupMemberPage,
  type GroupMemberSummary,
  type GroupPostPage,
  type GroupPostSummary,
  isEventFrame,
  isRateFrame,
  type LoginInput,
  type LoginResult,
  RATE_WINDOW_SECONDS,
  type RateCeilingSnapshot,
  type RateFrame,
  type RateLimitSnapshot,
  type RateSeries,
  RETENTION_DEFAULT_KEY,
  RETENTION_MAX_DAYS,
  RETENTION_MIN_DAYS,
  type RetentionKindStat,
  type RetentionRule,
  type RetentionRunResult,
  type RetentionSettings,
  type RetentionSource,
  type RetentionUpdate,
  STREAM_RATE,
  STREAM_READY,
  type StatusSnapshot,
  type StreamEnvelope,
  type StreamEventFrame,
  type StreamFrame,
  type TwoFactorMethod,
  type VerifyTwoFactorInput,
  type VerifyTwoFactorResult,
  type VrchatImageUrl,
  type WebhookRegistered,
  type WebhookRegistration,
  type WebhookSummary,
  type WorldInstanceList,
  type WorldInstanceOccupant,
  type WorldInstanceSource,
  type WorldInstanceSummary,
} from "./wire.ts";
