<!--
  Generated by the shadcn-svelte CLI, with a local fix. This project compiles with
  `exactOptionalPropertyTypes`, and the generated version forwards optional props as explicit
  `undefined`, which that flag rejects. Re-running `shadcn-svelte add` overwrites this file and
  brings the error back; reapply the fix below.
-->
<script lang="ts">
	import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";

	let {
		ref = $bindable(null),
		value = $bindable(""),
		...restProps
	}: DropdownMenuPrimitive.RadioGroupProps = $props();
</script>

<DropdownMenuPrimitive.RadioGroup
	bind:ref
	bind:value
	data-slot="dropdown-menu-radio-group"
	{...restProps}
/>
