/**
 * Generates the plugin reference: the JSON Schema, and the tables that would otherwise be
 * hand-maintained copies of code.
 *
 * Decision 182: **generated and committed, without a CI drift check.** The `packages/api` posture
 * — regenerate in CI, fail on a dirty tree — was declined here because these are docs rather than a
 * client whose staleness ships wrong requests. What they must not be is *hand-written*: a scope
 * table typed out beside a registry is a table that disagrees with the registry within two commits,
 * and the disagreement is invisible until somebody trusts the wrong half.
 *
 * Run with `bun run codegen:plugin-docs`.
 *
 * ## What is generated, and what is deliberately not
 *
 * Generated: the manifest's JSON Schema, the scope table, the capability table, the event catalog,
 * the port compatibility matrix, and the protocol limits. Every one of those is a projection of a
 * value that already exists in code.
 *
 * Not generated: the prose. `security-model.md`, `getting-started.md` and the mental model are
 * arguments, not projections — a generator that emitted them would be a template with the reasoning
 * removed.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  ALL_PLUGIN_CAPABILITIES,
  assignable,
  MAX_FRAME_BYTES,
  MAX_STORAGE_VALUE_BYTES,
  MAX_TABLE_ROWS,
  MAX_UI_DEPTH,
  MAX_UI_NODES,
  PLUGIN_CAPABILITIES,
  pluginManifestSchema,
  PORT_TYPES,
  PROTOCOL_ERRORS,
} from "@vrcz/plugin-api";
import { BUS_EVENT_KINDS, EVENT_FAMILIES, familyOf, SCOPES } from "@vrcz/shared";
import { z } from "zod";

const ROOT = resolve(import.meta.dir, "..", "..");
const DOCS = join(ROOT, "packages", "plugin-api", "docs", "generated");
const SCHEMA = join(ROOT, "packages", "plugin-api", "schema", "plugin.json");

/** The banner every generated page opens with. A reader has to know not to edit it. */
const BANNER = `<!-- Generated by \`bun run codegen:plugin-docs\`. Do not edit: change the code it reads. -->`;

function write(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents.endsWith("\n") ? contents : `${contents}\n`, "utf8");
  console.log(`  wrote ${path.slice(ROOT.length + 1)}`);
}

function scopeTable(): string {
  const rows = Object.entries(SCOPES)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([scope, info]) =>
        `| \`${scope}\` | ${info.dangerous ? "**yes**" : "no"} | ${info.description} |`,
    );
  return [
    BANNER,
    "",
    "# Scopes",
    "",
    "Every scope a plugin may request, with the sentence the consent screen shows for it.",
    "",
    "**Dangerous scopes sit behind a second toggle at consent and start unticked.** That is not a",
    "statement about the plugin asking for one — it is where the cost of being wrong is highest.",
    "",
    "| Scope | Dangerous | What the user is told |",
    "|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

function capabilityTable(): string {
  const rows = ALL_PLUGIN_CAPABILITIES.map((capability) => {
    const info = PLUGIN_CAPABILITIES[capability];
    return `| \`${capability}\` | ${info.dangerous ? "**yes**" : "no"} | ${info.description} |`;
  });
  return [
    BANNER,
    "",
    "# Capabilities",
    "",
    "Host powers, as distinct from scopes. A **scope** is authority over the user's VRChat account;",
    "a **capability** is a power of the host itself — a private database, a notification, an outbound",
    "request the host performs. They are separate because they fail differently and read differently",
    "to the person granting them.",
    "",
    "There is no `network` capability and no way to spell one. `webhook` and `fetch:allowlist` are",
    "its two narrow, host-executed replacements.",
    "",
    "| Capability | Dangerous | What the user is told |",
    "|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

function eventCatalog(): string {
  const byFamily = new Map<string, string[]>();
  for (const kind of BUS_EVENT_KINDS) {
    const family = familyOf(kind);
    const list = byFamily.get(family) ?? [];
    list.push(kind);
    byFamily.set(family, list);
  }

  const sections = [...EVENT_FAMILIES]
    .filter((family) => (byFamily.get(family) ?? []).length > 0)
    .map((family) => {
      const kinds = (byFamily.get(family) ?? []).sort();
      return [
        `## \`${family}.*\``,
        "",
        ...kinds.map((kind) => `- \`${kind}\``),
        "",
      ].join("\n");
    });

  return [
    BANNER,
    "",
    "# Event catalog",
    "",
    `Every event kind this build publishes: ${String(BUS_EVENT_KINDS.length)} kinds across`,
    `${String(EVENT_FAMILIES.length)} families.`,
    "",
    "Declare what you want in `permissions.events` — one exact kind, a whole family with",
    "`family.*`, or `*` for everything. **A family pattern is stable across versions and an exact",
    "kind is not**: a kind this build has never heard of matches `family.*` and no exact pattern, so",
    "an author who wants what a newer daemon adds writes the family.",
    "",
    "What you actually receive is the *intersection* of your scopes and these patterns. The narrower",
    "always wins, so a pattern cannot widen a scope you were not granted.",
    "",
    ...sections,
  ].join("\n");
}

function portMatrix(): string {
  const header = `| from \\ to | ${PORT_TYPES.map((type) => `\`${type}\``).join(" | ")} |`;
  const divider = `| --- | ${PORT_TYPES.map(() => "---").join(" | ")} |`;
  const rows = PORT_TYPES.map(
    (from) =>
      `| **\`${from}\`** | ${PORT_TYPES.map((to) => (assignable(from, to) ? "yes" : "—")).join(" | ")} |`,
  );
  return [
    BANNER,
    "",
    "# Port compatibility",
    "",
    "Generated from `assignable`, which is the single source of truth — this table cannot describe a",
    "rule that is not implemented.",
    "",
    "Two widening rules, and that is the whole list: `friend <: user`, and `X <: json`. Every",
    "additional rule would be an explanation you owe a user whose edge just got refused.",
    "",
    header,
    divider,
    ...rows,
    "",
  ].join("\n");
}

function limitsAndErrors(): string {
  const errors = Object.entries(PROTOCOL_ERRORS).map(
    ([code, info]) =>
      `| \`${code}\` | ${info.retryable ? "yes" : "no"} | ${info.description} |`,
  );
  return [
    BANNER,
    "",
    "# Limits and error codes",
    "",
    "## Limits",
    "",
    "| Limit | Value |",
    "|---|---|",
    `| Frame size | ${String(MAX_FRAME_BYTES)} bytes |`,
    `| UI tree nodes | ${String(MAX_UI_NODES)} |`,
    `| UI tree depth | ${String(MAX_UI_DEPTH)} |`,
    `| Table rows a plugin may send | ${String(MAX_TABLE_ROWS)} |`,
    "| Panels per plugin | 32 |",
    `| One stored value | ${String(MAX_STORAGE_VALUE_BYTES)} bytes |`,
    "",
    "These are not friction to be negotiated away. The host renders a plugin's tree eagerly on its",
    "own main thread, so they are what stands between a buggy plugin and a host-side stall.",
    "",
    "## Error codes",
    "",
    "`retryable` says whether waiting can help. `E_QUOTA` is not retryable because deleting is the",
    "fix; `E_RATE_LIMIT` is, and carries `retryAfterMs` — **retrying before it is a bug in your",
    "plugin**, and the user pays for it, not you.",
    "",
    "| Code | Retryable | What it means |",
    "|---|---|---|",
    ...errors,
    "",
  ].join("\n");
}

function main(): void {
  console.log("Generating the plugin reference…");

  /*
   * The JSON Schema an editor reads. A scaffolded manifest points its `$schema` at this file in the
   * repository, so completion works with no build step on the author's side.
   *
   * `unrepresentable: "any"` is required rather than chosen: `Scope` and `EventPattern` are
   * `z.custom` in the manifest — a *predicate*, which JSON Schema has no way to express — and
   * without this zod refuses to emit anything at all. The two lists that matter for completion are
   * then written back in as real enums below, from the same registries the validator uses, so an
   * editor offers exactly the strings the daemon accepts.
   */
  const jsonSchema = z.toJSONSchema(pluginManifestSchema, {
    io: "input",
    unrepresentable: "any",
  }) as Record<string, unknown>;

  const properties = (jsonSchema.properties ?? {}) as Record<string, Record<string, unknown>>;
  const permissions = (properties.permissions ?? {}) as Record<string, unknown>;
  const permissionProps = (permissions.properties ?? {}) as Record<string, Record<string, unknown>>;

  if (permissionProps.scopes !== undefined) {
    permissionProps.scopes.items = {
      type: "string",
      enum: Object.keys(SCOPES).sort(),
      description: "A scope from the shared registry. See docs/generated/scopes.md.",
    };
  }
  if (permissionProps.events !== undefined) {
    permissionProps.events.items = {
      type: "string",
      // `*`, every family wildcard, and every exact kind — the same three shapes the validator
      // accepts, enumerated so an editor can offer them.
      enum: ["*", ...EVENT_FAMILIES.map((family) => `${family}.*`), ...[...BUS_EVENT_KINDS].sort()],
      description: "An event pattern. See docs/generated/events.md.",
    };
  }
  if (permissionProps.capabilities !== undefined) {
    permissionProps.capabilities.items = {
      type: "string",
      enum: [...ALL_PLUGIN_CAPABILITIES].sort(),
      description: "A host capability. See docs/generated/capabilities.md.",
    };
  }

  write(
    SCHEMA,
    JSON.stringify(
      {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        title: "vrc.zip plugin manifest",
        ...jsonSchema,
      },
      null,
      2,
    ),
  );

  write(join(DOCS, "scopes.md"), scopeTable());
  write(join(DOCS, "capabilities.md"), capabilityTable());
  write(join(DOCS, "events.md"), eventCatalog());
  write(join(DOCS, "ports.md"), portMatrix());
  write(join(DOCS, "limits.md"), limitsAndErrors());

  console.log("Done. Commit what changed.");
}

main();
